"""rename address

Revision ID: 50b154253220
Revises: 4f18bc439100
Create Date: 2025-06-20 06:11:41.018572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b154253220'
down_revision = '4f18bc439100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments","address",new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments","location", new_column_name = "address")
    # ### end Alembic commands ###
